### PR TITLE
bugfixes, and add support for modern windows C runtimes

### LINKED ISSUE #13: CMD compatibility improvements
* mslex version: 1.2.0
* Python version: 3.13
* Operating System: Windows 11 23H2

I'd like to bring to your attention following test cases I came across while developing my parser [w32_lex](https://github.com/maxpat78/w32_lex).

With first 4, mslex differs completely from CMD method.

Next 4 differ only because mslex does not perform `%variables%` substitution, but it could.

Last 7 denote an approach that perhaps should be modified in mslex: `a&&b` etc. should isolate special operators like `&&` in `a && b`, to give the user better control.

```
note: mslex splits ":dir" differently: [':dir'] instead of []
note: mslex splits ";;;a,, b, c===" differently: [';;;a,,', 'b,', 'c==='] instead of ['a,,', 'b,', 'c===']
note: mslex splits "^;;a" differently: [';;a'] instead of [';', ';a']
note: mslex splits "a "<>||&&^" differently: ['a', '<>||&&'] instead of ['a', '<>||&&^']

note: mslex splits "dir %a%" differently: ['dir', '%a%'] instead of ['dir', '!subst!']
note: mslex splits "dir ^%a%" differently: ['dir', '%a%'] instead of ['dir', '!subst!']
note: mslex splits "dir %%a%%" differently: ['dir', '%%a%%'] instead of ['dir', '%!subst!%']
note: mslex splits "a "<>||&&%A%"" differently: ['a', '<>||&&%A%'] instead of ['a', '<>||&&!subst!']

note: mslex splits "@a	==b c" differently: ['@a', '==b', 'c'] instead of ['@', 'a', '==b', 'c']
note: mslex splits "a|b" differently: ['a|b'] instead of ['a', '|', 'b']
note: mslex splits "a||b" differently: ['a||b'] instead of ['a', '||', 'b']
note: mslex splits "a&b" differently: ['a&b'] instead of ['a', '&', 'b']
note: mslex splits "a&&b" differently: ['a&&b'] instead of ['a', '&&', 'b']
note: mslex splits "a>b" differently: ['a>b'] instead of ['a', '>', 'b']
note: mslex splits "a>>b||c" differently: ['a>>b||c'] instead of ['a', '>>', 'b', '||', 'c']
```

Thanks for your attention.

### PR DESCRIPTION
**Pull request by smoofra**
mslex.split did not correctly split command lines lines like 'foo"^'.

Also, unified the example lists in the test suite, and added a subprocess check to verify examples against cmd.exe.

### CODE REVIEW

**Comment by maxpat78** [comment]
I read about your doubts around MSVCRT != UCRT.

It seems to me there are not.

I've found a few CRT sources around (attached), of modern UCRT and old (1998 VS 6.0, 2005 VS 2005) argv parser, stripped down to compile only the parse_cmdline function (or UCRT equivalent) and export it as DLL to test with the following Python code:
```
stdargv = CDLL('.\\stdargv\\argv_parsing.dll')

def parse_cmdline(s):
    numargs = c_int(0)
    numchars = c_int(0)
    cmdline = create_string_buffer(s.encode())
    # void parse_cmdline(char *cmdstart, char **argv, char *args, int *numargs, int *numchars);
    stdargv.parse_cmdline(cmdline, c_void_p(0), c_char_p(0), byref(numargs), byref(numchars))

    argv = (c_char_p * numargs.value)()
    args = create_string_buffer(numchars.value)
    stdargv.parse_cmdline(cmdline, argv, args, byref(numargs), byref(numchars))

    # build a result list similar to ctypes_split
    r = []
    for i in range(0, numargs.value-1): # omit first command name (fake) and last NULL (None)
        r += [argv[i].decode()] # returns str, not bytes
    return r
```
Having analyzed the mslex test cases, it seems shareable that:
- CommandLineToArgvW parses the same since its introduction (obvious, it's a primary Win32 API!);
- C Runtime conforms to CommandLineToArgvW (simplified parsing of 1st arg, quote and backslashes rules, etc., for the others) with a _single_ exception:
- from 2005 onwards (VS 2005), a double quote `""` inside a quoted block emits a literal single quote `"` _but does not close the quoted block_. This rule is kept in the UCRT C++ code.

The bug fixed here is related to internal CMD parser rule: the first non-escaped quote `"` starts a quoted block that stops at next quote (that can't get escaped) or at line end, so the ending caret `^` has to be in the result - `a "<>||&&^` -> [CMD] -> `a "<>||&&^` -> [external CommandLineToArgvW] -> `[a] + [<>||&&^]`

[argv_parsing.cpp.txt](https://github.com/user-attachments/files/17348934/argv_parsing.cpp.txt)
[stdargv98.c.txt](https://github.com/user-attachments/files/17348935/stdargv98.c.txt)
[stdargv2005.c.txt](https://github.com/user-attachments/files/17348936/stdargv2005.c.txt)

**Comment by smoofra** [comment]
> I read about your doubts around MSVCRT != UCRT....

You can see from the tests I've added in this branch that the behavior is different.     `msvcrt.dll` and `CommandLineToArgvW` retain the old crazy mod3 behavior.     UCRT, and apparently VS 2005 have the new behavior as you've described.

If this behavior does date back to 2005, perhaps calling it "UCRT" here is not the best name.  Can you suggest a better one?

Fortunately it's not hard to create quoted strings that work with either C runtime.

**Comment by maxpat78** [comment]
If they at MS impose that name, keep it.
But, marketing apart, parse_cmdline substance did not change since 2005, it seems: except they moved to C++ in the last years.
Once you have a Win32 API like CommandLineToArgvW on which thousands apps rely on, it's very difficult make even small changes.

**Comment by smoofra** [comment]
They may have changed it in 2005, but that was for the redistributable `msvcr*.dll`, not the one that ships with windows.  I can link a program today and run it on windows 11 using the `msvcrt.dll` which has essentially been frozen since 1996. So it is important, particularly for quoting to support the old behavior because many programs are out there that are compiled that way, and we do not know which c library will be interpreting the strings we create.

**Comment by smoofra** [comment]
@petamas @jessielw 

If either of you have time to review this, I'd appreciate it.

**Review by jessielw — COMMENTED** [review]
Testing this it appears to work well and looks good. Good work on this!

**Comment by smoofra** [comment]
thanks, merged.

**Pull request merged**
